# Generated by Django 5.2.8 on 2025-12-15 19:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=150, unique=True)),
                ('type_structure', models.CharField(max_length=50)),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('devise', models.CharField(default='XOF', max_length=10)),
                ('actif', models.BooleanField(default=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'core_tenant',
            },
        ),
    ]
