# Generated by Django 6.0 on 2026-02-13 09:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=150, unique=True)),
                ('type_structure', models.CharField(max_length=50)),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('devise', models.CharField(default='XOF', max_length=10)),
                ('actif', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenants_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_tenant',
            },
        ),
    ]
