# Generated by Django 5.2.8 on 2025-12-17 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('stations', '0002_remove_ventecarburant_montant_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stations.station'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('SuperAdmin', 'SuperAdmin'), ('AdminTenant', 'AdminTenant'), ('Tresorier', 'Tresorier'), ('Collecteur', 'Collecteur'), ('Lecteur', 'Lecteur'), ('ChefStation', 'Chef de station'), ('Superviseur', 'Superviseur')], default='Lecteur', max_length=20),
        ),
    ]
