# Generated by Django 6.0 on 2025-12-21 10:21

from django.db import migrations, models


def forwards_func(apps, schema_editor):
    Utilisateur = apps.get_model("accounts", "Utilisateur")

    for user in Utilisateur.objects.all():

        # 🔥 RÈGLE N°1 — SuperAdmin absolu
        if user.is_superuser:
            user.role = "SuperAdmin"
            user.module = None
            user.station_id = None
            user.save(update_fields=["role", "module", "station"])
            continue

        # 🔁 Sécurité legacy : ChefStation → Gerant
        if user.role == "ChefStation":
            user.role = "Gerant"

        # 🔑 Attribution stricte du module
        if (
            user.role in [
                "Gerant",
                "Superviseur",
                "Pompiste",
                "Caissier",
                "PersonnelEntretien",
                "Securite",
                "Collecteur",
            ]
            or user.station_id is not None
        ):
            user.module = "station"
        else:
            # AdminTenant, Tresorier, Lecteur
            user.module = "finance"

        user.save(update_fields=["role", "module"])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_utilisateur_station_alter_utilisateur_role'),
        ('stations', '0002_remove_ventecarburant_montant_total_and_more'),
    ]

    operations = [
        # ✅ AJOUT DU CHAMP module
        migrations.AddField(
            model_name='utilisateur',
            name='module',
            field=models.CharField(
                blank=True,
                choices=[('finance', 'Finance'), ('station', 'Station')],
                max_length=20,
                null=True
            ),
        ),

        # ✅ AJOUT DE LA RELATION multi-stations
        migrations.AddField(
            model_name='utilisateur',
            name='stations_administrees',
            field=models.ManyToManyField(
                blank=True,
                related_name='admins',
                to='stations.station'
            ),
        ),

        # ✅ MISE À JOUR DES RÔLES
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(
                choices=[
                    ('SuperAdmin', 'SuperAdmin'),
                    ('AdminTenant', 'Administrateur'),
                    ('Tresorier', 'Trésorier'),
                    ('Gerant', 'Chef de station'),
                    ('Superviseur', 'Chef de piste'),
                    ('Pompiste', 'Agent de distribution'),
                    ('Caissier', 'Vendeur boutique'),
                    ('PersonnelEntretien', 'Nettoyage'),
                    ('Securite', 'Prévention des risques'),
                    ('Collecteur', 'Collecteur'),
                    ('Lecteur', 'Lecteur'),
                ],
                default='Lecteur',
                max_length=30
            ),
        ),

        # ✅ MIGRATION DES DONNÉES EXISTANTES
        migrations.RunPython(forwards_func),
    ]
