# Generated by Django 6.0 on 2025-12-27 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_utilisateur_module_utilisateur_stations_administrees_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('SuperAdmin', 'Super Admin'), ('AdminTenantFinance', 'Admin Tenant – Finance'), ('AdminTenantStation', 'Admin Tenant – Station'), ('Chef de station', 'Chef de station'), ('Collecteur', 'Collecteur'), ('Chef de piste', 'Chef de piste'), ('Trésorier', 'Trésorier'), ('Agent de distribution', 'Agent de distribution'), ('Vendeur boutique', 'Vendeur boutique'), ('Nettoyage', 'Nettoyage'), ('Prévention des risques', 'Prévention des risques')], default='Lecteur', max_length=30),
        ),
    ]
