# Generated by Django 6.0 on 2025-12-29 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_normalize_user_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('SUPERADMIN', 'Super Admin'), ('ADMIN_TENANT_FINANCE', 'Administrateur Finance'), ('ADMIN_TENANT_STATION', 'Administrateur Station'), ('GERANT', 'Chef de station'), ('SUPERVISEUR', 'Chef de piste'), ('POMPISTE', 'Agent de distribution'), ('CAISSIER', 'Vendeur boutique'), ('PERSONNEL_ENTRETIEN', 'Nettoyage'), ('SECURITE', 'Prévention des risques'), ('TRESORIER', 'Trésorier'), ('COLLECTEUR', 'Collecteur')], default='Lecteur', max_length=30),
        ),
    ]
