# Generated by Django 6.0 on 2026-03-04 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieDepense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories_depense', to='tenants.tenant')),
            ],
            options={
                'ordering': ['nom'],
                'unique_together': {('tenant', 'nom')},
            },
        ),
        migrations.CreateModel(
            name='ClientStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('telephone', models.CharField(blank=True, max_length=30)),
                ('plafond_credit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('actif', models.BooleanField(default=True)),
                ('valide_par_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients_station', to='tenants.tenant')),
            ],
            options={
                'ordering': ['nom'],
                'unique_together': {('tenant', 'nom')},
            },
        ),
        migrations.CreateModel(
            name='Ilot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ilots', to='tenants.tenant')),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='ModePaiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modes_paiement', to='tenants.tenant')),
            ],
            options={
                'ordering': ['nom'],
                'unique_together': {('tenant', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Pompe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(help_text='Référence physique de la pompe (ex: P1, P2)', max_length=50)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ilot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pompes', to='stations.ilot')),
            ],
            options={
                'ordering': ['reference'],
            },
        ),
        migrations.CreateModel(
            name='ProduitCarburant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=20)),
                ('seuil_critique_percent', models.DecimalField(decimal_places=2, default=10, help_text='Seuil critique en pourcentage de la capacité totale', max_digits=5)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits_carburant', to='tenants.tenant')),
            ],
            options={
                'ordering': ['code'],
                'unique_together': {('tenant', 'code')},
            },
        ),
        migrations.CreateModel(
            name='IndexPompe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_initial', models.DecimalField(decimal_places=2, max_digits=12)),
                ('index_courant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('face', models.CharField(choices=[('A', 'Face A'), ('B', 'Face B')], default='A', max_length=1)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pompe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='index_pompes', to='stations.pompe')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stations.produitcarburant')),
            ],
            options={
                'ordering': ['pompe', 'produit', 'face'],
            },
        ),
        migrations.CreateModel(
            name='Cuve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacite_max', models.DecimalField(decimal_places=2, max_digits=12)),
                ('stock_actuel', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('seuil_alerte', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('statut', models.CharField(choices=[('ACTIVE', 'Active (ouverte)'), ('STANDBY', 'En attente'), ('EN_DEPOTAGE', 'En dépotage'), ('MAINTENANCE', 'Maintenance'), ('HORS_SERVICE', 'Hors service')], default='STANDBY', max_length=20)),
                ('reference', models.CharField(editable=False, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuves', to='stations.produitcarburant')),
            ],
        ),
        migrations.CreateModel(
            name='RelaisEquipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debut_relais', models.DateTimeField()),
                ('fin_relais', models.DateTimeField()),
                ('equipe_sortante', models.CharField(max_length=100)),
                ('equipe_entrante', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('SOUMIS', 'Soumis'), ('VALIDE', 'Validé'), ('TRANSFERE', 'Transféré')], default='BROUILLON', max_length=20)),
                ('stock_applique', models.BooleanField(default=False)),
                ('soumis_le', models.DateTimeField(blank=True, null=True)),
                ('valide_le', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relais_crees', to=settings.AUTH_USER_MODEL)),
                ('soumis_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relais_soumis', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relais_equipes', to='tenants.tenant')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relais_valides', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RelaisAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ancien_statut', models.CharField(max_length=20)),
                ('nouveau_statut', models.CharField(max_length=20)),
                ('action', models.CharField(max_length=50)),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('effectue_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('relais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='stations.relaisequipe')),
            ],
            options={
                'ordering': ['-date_action'],
            },
        ),
        migrations.CreateModel(
            name='DetteJournalier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_initial', models.DecimalField(decimal_places=2, max_digits=14)),
                ('montant_regle', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('PARTIELLE', 'Partiellement réglée'), ('REGLEE', 'Réglée')], default='EN_ATTENTE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dettes', to='stations.clientstation')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('relais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dettes', to='stations.relaisequipe')),
            ],
        ),
        migrations.CreateModel(
            name='DepenseJournalier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=14)),
                ('description', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('VALIDE', 'Validé'), ('TRANSFERE', 'Transféré')], default='BROUILLON', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stations.categoriedepense')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='depenses_creees', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='depenses_validees', to=settings.AUTH_USER_MODEL)),
                ('relais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depenses', to='stations.relaisequipe')),
            ],
        ),
        migrations.CreateModel(
            name='RelaisIlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('SOUMIS', 'Soumis'), ('VALIDE', 'Validé'), ('TRANSFERE', 'Transféré')], default='BROUILLON', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relais_ilots_crees', to=settings.AUTH_USER_MODEL)),
                ('ilot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relais', to='stations.ilot')),
                ('relais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ilots', to='stations.relaisequipe')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relais_ilots_responsable', to=settings.AUTH_USER_MODEL)),
                ('soumis_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='relais_ilots_soumis', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relais_ilots', to='tenants.tenant')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='relais_ilots_valides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='RelaisEcart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_ecart', models.CharField(choices=[('MANQUE', 'Manque'), ('EXCEDENT', 'Excédent')], max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ecarts_relais', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relais_ecarts', to='tenants.tenant')),
                ('relais_ilot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ecart', to='stations.relaisilot')),
            ],
        ),
        migrations.CreateModel(
            name='EncaissementRelais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=14)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('mode_paiement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stations.modepaiement')),
                ('relais_ilot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encaissements', to='stations.relaisilot')),
            ],
        ),
        migrations.CreateModel(
            name='RelaisIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_debut', models.DecimalField(decimal_places=2, max_digits=12)),
                ('index_fin', models.DecimalField(decimal_places=2, max_digits=12)),
                ('prix_unitaire', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('montant_theorique', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('index_pompe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stations.indexpompe')),
                ('relais_ilot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indexes', to='stations.relaisilot')),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('region', models.CharField(blank=True, choices=[('Dakar', 'Dakar'), ('Thiès', 'Thiès'), ('Diourbel', 'Diourbel'), ('Fatick', 'Fatick'), ('Kaolack', 'Kaolack'), ('Kaffrine', 'Kaffrine'), ('Tambacounda', 'Tambacounda'), ('Kédougou', 'Kédougou'), ('Sédhiou', 'Sédhiou'), ('Kolda', 'Kolda'), ('Ziguinchor', 'Ziguinchor'), ('Louga', 'Louga'), ('Matam', 'Matam'), ('Saint-Louis', 'Saint-Louis')], max_length=100, null=True)),
                ('departement', models.CharField(blank=True, max_length=100, null=True)),
                ('adresse', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='tenants.tenant')),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.AddField(
            model_name='relaisequipe',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relais_equipes', to='stations.station'),
        ),
        migrations.CreateModel(
            name='PrixCarburant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('actif', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prix_carburants', to='tenants.tenant')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prix', to='stations.produitcarburant')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prix_carburants', to='stations.station')),
            ],
            options={
                'ordering': ['-date_debut'],
            },
        ),
        migrations.AddField(
            model_name='pompe',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pompes', to='stations.station'),
        ),
        migrations.CreateModel(
            name='ObjectifStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.IntegerField()),
                ('mois', models.IntegerField()),
                ('volume_cible', models.DecimalField(decimal_places=2, max_digits=14)),
                ('ca_cible', models.DecimalField(decimal_places=2, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectifs_stations', to='tenants.tenant')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectifs', to='stations.produitcarburant')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectifs', to='stations.station')),
            ],
        ),
        migrations.CreateModel(
            name='MouvementStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_mouvement', models.CharField(choices=[('ENTREE', 'Entrée'), ('SORTIE', 'Sortie')], max_length=10)),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=12)),
                ('source_type', models.CharField(max_length=50)),
                ('source_id', models.PositiveIntegerField()),
                ('date_mouvement', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cuve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stations.cuve')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stations.station')),
            ],
            options={
                'ordering': ['-date_mouvement'],
            },
        ),
        migrations.AddField(
            model_name='ilot',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ilots', to='stations.station'),
        ),
        migrations.CreateModel(
            name='Depotage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fournisseur', models.CharField(max_length=150)),
                ('date_depotage', models.DateTimeField()),
                ('quantite_commandee', models.DecimalField(blank=True, decimal_places=2, help_text='Quantité initialement commandée (optionnelle)', max_digits=10, null=True)),
                ('quantite_livree', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantite_acceptee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('jauge_avant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('jauge_apres', models.DecimalField(decimal_places=2, max_digits=10)),
                ('variation_cuve', models.DecimalField(decimal_places=2, help_text='Calculé : jauge_apres - jauge_avant', max_digits=10)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('bon_livraison_numero', models.CharField(blank=True, max_length=100, null=True)),
                ('stock_applique', models.BooleanField(default=False, help_text="Indique si l'impact stock a déjà été appliqué")),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('SOUMIS', 'Soumis'), ('CONFIRME', 'Confirmé'), ('TRANSFERE', 'Transféré')], default='BROUILLON', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference_commande', models.CharField(blank=True, help_text='Référence commande fournisseur (phase 2)', max_length=100, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depotages_crees', to=settings.AUTH_USER_MODEL)),
                ('cuve', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='depotages', to='stations.cuve')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depotages', to='tenants.tenant')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depotages_valides', to=settings.AUTH_USER_MODEL)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depotages', to='stations.station')),
            ],
            options={
                'verbose_name': 'Dépotage',
                'verbose_name_plural': 'Dépotages',
                'ordering': ['-date_depotage'],
            },
        ),
        migrations.AddField(
            model_name='cuve',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stations.station'),
        ),
        migrations.CreateModel(
            name='Versement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_remis', models.DecimalField(decimal_places=2, max_digits=14)),
                ('date_versement', models.DateField()),
                ('reference', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('relais_ilot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versements', to='stations.relaisilot')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
        ),
        migrations.AddConstraint(
            model_name='indexpompe',
            constraint=models.UniqueConstraint(fields=('pompe', 'produit', 'face'), name='unique_index_par_face'),
        ),
        migrations.AddIndex(
            model_name='relaisaudit',
            index=models.Index(fields=['relais', 'date_action'], name='stations_re_relais__2672db_idx'),
        ),
        migrations.AddIndex(
            model_name='dettejournalier',
            index=models.Index(fields=['tenant', 'relais'], name='stations_de_tenant__52f311_idx'),
        ),
        migrations.AddIndex(
            model_name='dettejournalier',
            index=models.Index(fields=['tenant', 'client'], name='stations_de_tenant__e45109_idx'),
        ),
        migrations.AddIndex(
            model_name='depensejournalier',
            index=models.Index(fields=['tenant', 'relais'], name='stations_de_tenant__7e1c10_idx'),
        ),
        migrations.AddIndex(
            model_name='relaisilot',
            index=models.Index(fields=['tenant', 'relais'], name='stations_re_tenant__452d92_idx'),
        ),
        migrations.AddIndex(
            model_name='relaisilot',
            index=models.Index(fields=['relais', 'statut'], name='stations_re_relais__809551_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='relaisilot',
            unique_together={('relais', 'ilot')},
        ),
        migrations.AddIndex(
            model_name='relaisecart',
            index=models.Index(fields=['tenant', 'responsable'], name='stations_re_tenant__b1d141_idx'),
        ),
        migrations.AddIndex(
            model_name='encaissementrelais',
            index=models.Index(fields=['tenant', 'relais_ilot'], name='stations_en_tenant__106c64_idx'),
        ),
        migrations.AddConstraint(
            model_name='relaisindex',
            constraint=models.UniqueConstraint(fields=('relais_ilot', 'index_pompe'), name='unique_index_per_relais_ilot'),
        ),
        migrations.AddIndex(
            model_name='relaisequipe',
            index=models.Index(fields=['station', 'debut_relais', 'fin_relais'], name='idx_station_periode_relais'),
        ),
        migrations.AddIndex(
            model_name='relaisequipe',
            index=models.Index(fields=['tenant', 'status', 'fin_relais'], name='idx_tenant_status_periode'),
        ),
        migrations.AddConstraint(
            model_name='prixcarburant',
            constraint=models.UniqueConstraint(condition=models.Q(('actif', True)), fields=('tenant', 'station', 'produit'), name='unique_prix_actif_par_produit_tenant'),
        ),
        migrations.AlterUniqueTogether(
            name='pompe',
            unique_together={('station', 'reference')},
        ),
        migrations.AddIndex(
            model_name='objectifstation',
            index=models.Index(fields=['tenant', 'annee', 'mois'], name='stations_ob_tenant__6784ce_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='objectifstation',
            unique_together={('tenant', 'station', 'produit', 'annee', 'mois')},
        ),
        migrations.AlterUniqueTogether(
            name='ilot',
            unique_together={('station', 'nom')},
        ),
        migrations.AddConstraint(
            model_name='cuve',
            constraint=models.UniqueConstraint(condition=models.Q(('statut', 'ACTIVE')), fields=('station', 'produit'), name='unique_active_cuve_per_product_station'),
        ),
        migrations.AddConstraint(
            model_name='cuve',
            constraint=models.UniqueConstraint(fields=('station', 'reference'), name='unique_cuve_reference_per_station'),
        ),
        migrations.AddIndex(
            model_name='versement',
            index=models.Index(fields=['tenant', 'relais_ilot'], name='stations_ve_tenant__2b01bb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='versement',
            unique_together={('relais_ilot',)},
        ),
    ]
