# Generated by Django 6.0 on 2026-02-17 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProduitCarburant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=20)),
                ('seuil_critique_percent', models.DecimalField(decimal_places=2, default=10, help_text='Seuil critique en pourcentage de la capacité totale', max_digits=5)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits_carburant', to='tenants.tenant')),
            ],
            options={
                'ordering': ['code'],
                'unique_together': {('tenant', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Cuve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacite_max', models.DecimalField(decimal_places=2, max_digits=12)),
                ('stock_actuel', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('seuil_alerte', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('statut', models.CharField(choices=[('ACTIVE', 'Active (ouverte)'), ('STANDBY', 'En attente'), ('EN_DEPOTAGE', 'En dépotage'), ('MAINTENANCE', 'Maintenance'), ('HORS_SERVICE', 'Hors service')], default='STANDBY', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuves', to='stations.produitcarburant')),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('region', models.CharField(blank=True, choices=[('Dakar', 'Dakar'), ('Thiès', 'Thiès'), ('Diourbel', 'Diourbel'), ('Fatick', 'Fatick'), ('Kaolack', 'Kaolack'), ('Kaffrine', 'Kaffrine'), ('Tambacounda', 'Tambacounda'), ('Kédougou', 'Kédougou'), ('Sédhiou', 'Sédhiou'), ('Kolda', 'Kolda'), ('Ziguinchor', 'Ziguinchor'), ('Louga', 'Louga'), ('Matam', 'Matam'), ('Saint-Louis', 'Saint-Louis')], max_length=100, null=True)),
                ('departement', models.CharField(blank=True, max_length=100, null=True)),
                ('adresse', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='tenants.tenant')),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='RelaisEquipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debut_relais', models.DateTimeField()),
                ('fin_relais', models.DateTimeField()),
                ('equipe_sortante', models.CharField(max_length=100)),
                ('equipe_entrante', models.CharField(max_length=100)),
                ('encaisse_liquide', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('encaisse_carte', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('SOUMIS', 'Soumis'), ('VALIDE', 'Validé'), ('TRANSFERE', 'Transféré')], default='BROUILLON', max_length=20)),
                ('stock_applique', models.BooleanField(default=False)),
                ('soumis_le', models.DateTimeField(blank=True, null=True)),
                ('valide_le', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relais_crees', to=settings.AUTH_USER_MODEL)),
                ('soumis_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relais_soumis', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relais_equipes', to='tenants.tenant')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relais_valides', to=settings.AUTH_USER_MODEL)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relais_equipes', to='stations.station')),
            ],
        ),
        migrations.CreateModel(
            name='Pompe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(help_text='Référence physique de la pompe (ex: P1, P2)', max_length=50)),
                ('type_pompe', models.CharField(choices=[('SIMPLE', 'Simple'), ('MIXTE', 'Mixte')], max_length=10)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pompes', to='stations.station')),
            ],
            options={
                'ordering': ['reference'],
            },
        ),
        migrations.CreateModel(
            name='MouvementStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_mouvement', models.CharField(choices=[('ENTREE', 'Entrée'), ('SORTIE', 'Sortie')], max_length=10)),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=12)),
                ('source_type', models.CharField(max_length=50)),
                ('source_id', models.PositiveIntegerField()),
                ('date_mouvement', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cuve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stations.cuve')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stations.station')),
            ],
            options={
                'ordering': ['-date_mouvement'],
            },
        ),
        migrations.CreateModel(
            name='Depotage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fournisseur', models.CharField(max_length=150)),
                ('date_depotage', models.DateTimeField()),
                ('quantite_commandee', models.DecimalField(blank=True, decimal_places=2, help_text='Quantité initialement commandée (optionnelle)', max_digits=10, null=True)),
                ('quantite_livree', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantite_acceptee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('jauge_avant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('jauge_apres', models.DecimalField(decimal_places=2, max_digits=10)),
                ('variation_cuve', models.DecimalField(decimal_places=2, help_text='Calculé : jauge_apres - jauge_avant', max_digits=10)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('bon_livraison_numero', models.CharField(blank=True, max_length=100, null=True)),
                ('stock_applique', models.BooleanField(default=False, help_text="Indique si l'impact stock a déjà été appliqué")),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('SOUMIS', 'Soumis'), ('CONFIRME', 'Confirmé')], default='BROUILLON', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference_commande', models.CharField(blank=True, help_text='Référence commande fournisseur (phase 2)', max_length=100, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depotages_crees', to=settings.AUTH_USER_MODEL)),
                ('cuve', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='depotages', to='stations.cuve')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depotages', to='tenants.tenant')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depotages_valides', to=settings.AUTH_USER_MODEL)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depotages', to='stations.station')),
            ],
            options={
                'verbose_name': 'Dépotage',
                'verbose_name_plural': 'Dépotages',
                'ordering': ['-date_depotage'],
            },
        ),
        migrations.AddField(
            model_name='cuve',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stations.station'),
        ),
        migrations.CreateModel(
            name='IndexPompe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_initial', models.DecimalField(decimal_places=2, max_digits=12)),
                ('index_courant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('face', models.CharField(choices=[('A', 'Face A'), ('B', 'Face B')], default='A', max_length=1)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pompe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='index_pompes', to='stations.pompe')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stations.produitcarburant')),
            ],
            options={
                'ordering': ['pompe', 'produit', 'face'],
                'constraints': [models.UniqueConstraint(fields=('pompe', 'produit', 'face'), name='unique_index_par_face')],
            },
        ),
        migrations.CreateModel(
            name='RelaisAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ancien_statut', models.CharField(max_length=20)),
                ('nouveau_statut', models.CharField(max_length=20)),
                ('action', models.CharField(max_length=50)),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('effectue_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('relais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='stations.relaisequipe')),
            ],
            options={
                'ordering': ['-date_action'],
                'indexes': [models.Index(fields=['relais', 'date_action'], name='stations_re_relais__2672db_idx')],
            },
        ),
        migrations.CreateModel(
            name='RelaisProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_debut', models.DecimalField(decimal_places=2, max_digits=12)),
                ('index_fin', models.DecimalField(decimal_places=2, max_digits=12)),
                ('encaisse_ticket', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stations.produitcarburant')),
                ('relais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='stations.relaisequipe')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('relais', 'produit'), name='unique_produit_per_relais')],
            },
        ),
        migrations.AddIndex(
            model_name='relaisequipe',
            index=models.Index(fields=['station', 'debut_relais', 'fin_relais'], name='idx_station_periode_relais'),
        ),
        migrations.AlterUniqueTogether(
            name='pompe',
            unique_together={('station', 'reference')},
        ),
        migrations.AddConstraint(
            model_name='cuve',
            constraint=models.UniqueConstraint(condition=models.Q(('statut', 'ACTIVE')), fields=('station', 'produit'), name='unique_active_cuve_per_product_station'),
        ),
        migrations.AddConstraint(
            model_name='cuve',
            constraint=models.UniqueConstraint(fields=('station', 'reference'), name='unique_cuve_reference_per_station'),
        ),
    ]
