# Generated by Django 6.0 on 2026-02-14 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuve',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='cuve',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='depotage',
            name='produit',
        ),
        migrations.AddField(
            model_name='cuve',
            name='statut',
            field=models.CharField(choices=[('ACTIVE', 'Active (ouverte)'), ('STANDBY', 'En attente'), ('EN_DEPOTAGE', 'En dépotage'), ('MAINTENANCE', 'Maintenance'), ('HORS_SERVICE', 'Hors service')], default='STANDBY', max_length=20),
        ),
        migrations.AddField(
            model_name='depotage',
            name='cuve',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='depotages', to='stations.cuve'),
        ),
        migrations.AddField(
            model_name='depotage',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='depotages', to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='cuve',
            name='capacite_max',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='cuve',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stations.station'),
        ),
        migrations.AlterField(
            model_name='cuve',
            name='stock_actuel',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='cuve',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='depotage',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='depotages', to='stations.station'),
        ),
        migrations.CreateModel(
            name='ProduitCarburant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=20)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits_carburant', to='tenants.tenant')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.AlterField(
            model_name='cuve',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stations.produitcarburant'),
        ),
        migrations.AddConstraint(
            model_name='cuve',
            constraint=models.UniqueConstraint(condition=models.Q(('statut', 'ACTIVE')), fields=('station', 'produit'), name='unique_active_cuve_per_product_station'),
        ),
        migrations.RemoveField(
            model_name='cuve',
            name='actif',
        ),
        migrations.AlterUniqueTogether(
            name='produitcarburant',
            unique_together={('tenant', 'code')},
        ),
    ]
