# Generated by Django 6.0 on 2026-02-17 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuve',
            name='reference',
            field=models.CharField(help_text='Identifiant métier (ex: CUV-ESS-01)', max_length=50),
        ),
    ]
