# Generated by Django 6.0 on 2026-03-05 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ilot',
            index=models.Index(fields=['tenant', 'station'], name='stations_il_tenant__f56e79_idx'),
        ),
    ]
