# Generated by Django 5.2.8 on 2025-12-16 22:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventecarburant',
            name='montant_total',
        ),
        migrations.AddField(
            model_name='ventecarburant',
            name='soumis_le',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ventecarburant',
            name='soumis_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventes_soumises', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ventecarburant',
            name='status',
            field=models.CharField(choices=[('BROUILLON', 'Brouillon'), ('SOUMIS', 'Soumis'), ('VALIDE', 'Validé'), ('TRANSFERE', 'Transféré')], default='BROUILLON', max_length=20),
        ),
        migrations.AddField(
            model_name='ventecarburant',
            name='valide_le',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ventecarburant',
            name='valide_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventes_validees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ventecarburant',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventes_creees', to=settings.AUTH_USER_MODEL),
        ),
    ]
