# Generated by Django 6.0 on 2026-02-27 22:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='relaisequipe',
            index=models.Index(fields=['tenant', 'status', 'fin_relais'], name='idx_tenant_status_periode'),
        ),
    ]
