# Generated by Django 6.0 on 2026-02-15 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0002_alter_cuve_options_alter_cuve_unique_together_and_more'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depotage',
            name='cuve',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='depotages', to='stations.cuve'),
        ),
        migrations.AlterField(
            model_name='depotage',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depotages', to='stations.station'),
        ),
        migrations.AlterField(
            model_name='depotage',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depotages', to='tenants.tenant'),
        ),
    ]
