# Generated by Django 6.0 on 2026-02-18 10:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0002_alter_cuve_reference'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relaisproduit',
            name='encaisse_ticket',
        ),
        migrations.AddField(
            model_name='relaisequipe',
            name='encaisse_ticket',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='relaisproduit',
            name='montant_theorique',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='relaisproduit',
            name='prix_unitaire',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.CreateModel(
            name='PrixCarburant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('actif', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prix', to='stations.produitcarburant')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prix_carburants', to='stations.station')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prix_carburants', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-date_debut'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('actif', True)), fields=('tenant', 'station', 'produit'), name='unique_prix_actif_par_produit_tenant')],
            },
        ),
    ]
