# Generated by Django 6.0 on 2026-02-28 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0002_relaisequipe_idx_tenant_status_periode'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectifStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.IntegerField()),
                ('mois', models.IntegerField()),
                ('volume_cible', models.DecimalField(decimal_places=2, max_digits=14)),
                ('ca_cible', models.DecimalField(decimal_places=2, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectifs', to='stations.produitcarburant')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectifs', to='stations.station')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectifs_stations', to='tenants.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'annee', 'mois'], name='stations_ob_tenant__6784ce_idx')],
                'unique_together': {('station', 'produit', 'annee', 'mois')},
            },
        ),
    ]
