# Generated by Django 6.0 on 2025-12-28 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0002_remove_ventecarburant_montant_total_and_more'),
        ('tenants', '0002_alter_tenant_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventecarburant',
            name='produit',
            field=models.CharField(choices=[('Super', 'Super'), ('Gasoil', 'Gasoil')], max_length=50),
        ),
        migrations.CreateModel(
            name='RelaisEquipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debut_relais', models.DateTimeField()),
                ('fin_relais', models.DateTimeField()),
                ('equipe_sortante', models.CharField(max_length=100)),
                ('equipe_entrante', models.CharField(max_length=100)),
                ('index_essence_debut', models.DecimalField(decimal_places=2, max_digits=12)),
                ('index_essence_fin', models.DecimalField(decimal_places=2, max_digits=12)),
                ('index_gasoil_debut', models.DecimalField(decimal_places=2, max_digits=12)),
                ('index_gasoil_fin', models.DecimalField(decimal_places=2, max_digits=12)),
                ('jauge_essence_debut', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('jauge_essence_fin', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('jauge_gasoil_debut', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('jauge_gasoil_fin', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('encaisse_liquide', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('encaisse_carte', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('encaisse_ticket_essence', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('encaisse_ticket_gasoil', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('SOUMIS', 'Soumis'), ('VALIDE', 'Validé'), ('TRANSFERE', 'Transféré')], default='BROUILLON', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('soumis_le', models.DateTimeField(blank=True, null=True)),
                ('valide_le', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relais_crees', to=settings.AUTH_USER_MODEL)),
                ('soumis_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relais_soumis', to=settings.AUTH_USER_MODEL)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relais_equipes', to='stations.station')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relais_equipes', to='tenants.tenant')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relais_valides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Relais d’équipe',
                'verbose_name_plural': 'Relais d’équipes',
                'ordering': ['-debut_relais'],
                'indexes': [models.Index(fields=['station', 'debut_relais'], name='stations_re_station_9b02fb_idx')],
            },
        ),
    ]
