# Generated by Django 6.0 on 2026-03-06 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0002_ilot_stations_il_tenant__f56e79_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relaisindex',
            name='index_fin',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
