# Generated by Django 6.0 on 2026-03-06 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0003_alter_relaisindex_index_fin'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='relaisilot',
            name='stations_re_relais__809551_idx',
        ),
        migrations.RemoveField(
            model_name='relaisilot',
            name='statut',
        ),
    ]
