# Generated by Django 6.0 on 2026-02-15 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0003_alter_depotage_cuve_alter_depotage_station_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelaisProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_debut', models.DecimalField(decimal_places=2, max_digits=12)),
                ('index_fin', models.DecimalField(decimal_places=2, max_digits=12)),
                ('jauge_debut', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('jauge_fin', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('encaisse_ticket', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
        ),
        migrations.AlterModelOptions(
            name='relaisequipe',
            options={'ordering': ['-debut_relais']},
        ),
        migrations.RemoveIndex(
            model_name='relaisequipe',
            name='stations_re_station_9b02fb_idx',
        ),
        migrations.AlterField(
            model_name='relaisequipe',
            name='stock_applique',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='relaisproduit',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stations.produitcarburant'),
        ),
        migrations.AddField(
            model_name='relaisproduit',
            name='relais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='stations.relaisequipe'),
        ),
        migrations.RemoveField(
            model_name='relaisequipe',
            name='encaisse_ticket_essence',
        ),
        migrations.RemoveField(
            model_name='relaisequipe',
            name='encaisse_ticket_gasoil',
        ),
        migrations.RemoveField(
            model_name='relaisequipe',
            name='index_essence_debut',
        ),
        migrations.RemoveField(
            model_name='relaisequipe',
            name='index_essence_fin',
        ),
        migrations.RemoveField(
            model_name='relaisequipe',
            name='index_gasoil_debut',
        ),
        migrations.RemoveField(
            model_name='relaisequipe',
            name='index_gasoil_fin',
        ),
        migrations.RemoveField(
            model_name='relaisequipe',
            name='jauge_essence_debut',
        ),
        migrations.RemoveField(
            model_name='relaisequipe',
            name='jauge_essence_fin',
        ),
        migrations.RemoveField(
            model_name='relaisequipe',
            name='jauge_gasoil_debut',
        ),
        migrations.RemoveField(
            model_name='relaisequipe',
            name='jauge_gasoil_fin',
        ),
        migrations.RemoveField(
            model_name='relaisequipe',
            name='soumis_le',
        ),
        migrations.RemoveField(
            model_name='relaisequipe',
            name='soumis_par',
        ),
        migrations.RemoveField(
            model_name='relaisequipe',
            name='valide_le',
        ),
        migrations.RemoveField(
            model_name='relaisequipe',
            name='valide_par',
        ),
        migrations.AlterUniqueTogether(
            name='relaisproduit',
            unique_together={('relais', 'produit')},
        ),
    ]
