# Generated by Django 6.0 on 2026-02-18 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0003_remove_relaisproduit_encaisse_ticket_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pompe',
            name='type_pompe',
        ),
    ]
