# Generated by Django 6.0 on 2025-12-30 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0003_alter_ventecarburant_produit_relaisequipe'),
        ('tenants', '0002_alter_tenant_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='departement',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='station',
            name='region',
            field=models.CharField(blank=True, choices=[('Dakar', 'Dakar'), ('Thiès', 'Thiès'), ('Diourbel', 'Diourbel'), ('Fatick', 'Fatick'), ('Kaolack', 'Kaolack'), ('Kaffrine', 'Kaffrine'), ('Tambacounda', 'Tambacounda'), ('Kédougou', 'Kédougou'), ('Sédhiou', 'Sédhiou'), ('Kolda', 'Kolda'), ('Ziguinchor', 'Ziguinchor'), ('Louga', 'Louga'), ('Matam', 'Matam'), ('Saint-Louis', 'Saint-Louis')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='tenants.tenant'),
        ),
    ]
