# Generated by Django 6.0 on 2026-03-01 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0003_objectifstation'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='objectifstation',
            unique_together={('tenant', 'station', 'produit', 'annee', 'mois')},
        ),
    ]
