# Generated by Django 6.0 on 2026-01-04 23:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0004_station_departement_station_region_and_more'),
        ('tenants', '0002_alter_tenant_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produit', models.CharField(choices=[('ESSENCE', 'Essence'), ('GASOIL', 'Gasoil')], max_length=20)),
                ('capacite_max', models.DecimalField(decimal_places=2, help_text='Capacité maximale de la cuve', max_digits=12)),
                ('stock_actuel', models.DecimalField(decimal_places=2, default=0, help_text='Stock actuel en litres', max_digits=12)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuves', to='stations.station')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuves', to='tenants.tenant')),
            ],
            options={
                'ordering': ['station', 'produit'],
                'unique_together': {('station', 'produit')},
            },
        ),
        migrations.CreateModel(
            name='Depotage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produit', models.CharField(choices=[('ESSENCE', 'Essence'), ('GASOIL', 'Gasoil')], max_length=10)),
                ('fournisseur', models.CharField(max_length=150)),
                ('date_depotage', models.DateTimeField()),
                ('quantite_commandee', models.DecimalField(blank=True, decimal_places=2, help_text='Quantité initialement commandée (optionnelle)', max_digits=10, null=True)),
                ('quantite_livree', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantite_acceptee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('jauge_avant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('jauge_apres', models.DecimalField(decimal_places=2, max_digits=10)),
                ('variation_cuve', models.DecimalField(decimal_places=2, help_text='Calculé : jauge_apres - jauge_avant', max_digits=10)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('bon_livraison_numero', models.CharField(blank=True, max_length=100, null=True)),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('SOUMIS', 'Soumis'), ('CONFIRME', 'Confirmé')], default='BROUILLON', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference_commande', models.CharField(blank=True, help_text='Référence commande fournisseur (phase 2)', max_length=100, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depotages_crees', to=settings.AUTH_USER_MODEL)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depotages', to='stations.station')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depotages_valides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dépotage',
                'verbose_name_plural': 'Dépotages',
                'ordering': ['-date_depotage'],
            },
        ),
        migrations.CreateModel(
            name='MouvementStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_mouvement', models.CharField(choices=[('ENTREE', 'Entrée'), ('SORTIE', 'Sortie')], max_length=10)),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=12)),
                ('source_type', models.CharField(max_length=50)),
                ('source_id', models.PositiveIntegerField()),
                ('date_mouvement', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cuve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stations.cuve')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stations.station')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'ordering': ['-date_mouvement'],
            },
        ),
    ]
