# Generated by Django 6.0 on 2026-02-15 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0004_relaisproduit_alter_relaisequipe_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='relaisproduit',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='relaisproduit',
            constraint=models.UniqueConstraint(fields=('relais', 'produit'), name='unique_produit_per_relais'),
        ),
    ]
