# Generated by Django 6.0 on 2026-03-06 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0004_remove_relaisilot_stations_re_relais__809551_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modepaiement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='modepaiement',
            name='actif',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
