# Generated by Django 6.0 on 2026-02-15 08:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0005_alter_relaisproduit_unique_together_and_more'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='relaisequipe',
            options={},
        ),
        migrations.AddIndex(
            model_name='relaisequipe',
            index=models.Index(fields=['station', 'debut_relais', 'fin_relais'], name='idx_station_periode_relais'),
        ),
    ]
