# Generated by Django 6.0 on 2026-03-08 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0005_modepaiement_updated_at_alter_modepaiement_actif'),
    ]

    operations = [
        migrations.AddField(
            model_name='depotage',
            name='chauffeur',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='depotage',
            name='date_commande',
            field=models.DateField(blank=True, help_text='Date de la commande fournisseur', null=True),
        ),
        migrations.AddField(
            model_name='depotage',
            name='ecart_depotage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Ecart entre quantité acceptée et variation cuve', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='depotage',
            name='manquant_camion',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Quantité manquante camion (BL - volume mesuré)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='depotage',
            name='numero_camion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='depotage',
            name='temperature',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Température carburant (°C)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='depotage',
            name='transporteur',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
