# Generated by Django 6.0 on 2026-01-05 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0006_cuve_seuil_alerte_justificationdepotage'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='cuve',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='depotages', to='stations.cuve'),
        ),
    ]
