# Generated by Django 6.0 on 2026-03-08 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0006_depotage_chauffeur_depotage_date_commande_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VersementDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=14)),
                ('mode_paiement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stations.modepaiement')),
                ('versement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='stations.versement')),
            ],
            options={
                'unique_together': {('versement', 'mode_paiement')},
            },
        ),
    ]
