# Generated by Django 6.0 on 2026-01-05 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0007_station_cuve'),
    ]

    operations = [
        migrations.AddField(
            model_name='relaisequipe',
            name='stock_applique',
            field=models.BooleanField(default=False, help_text='Indique si le stock a déjà été décrémenté pour ce relais'),
        ),
    ]
