# Generated by Django 6.0 on 2026-03-14 22:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0007_versementdetail'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=14)),
                ('description', models.TextField(blank=True)),
                ('date_depense', models.DateField()),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('VALIDE', 'Validé')], default='BROUILLON', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='depensejournalier',
            name='stations_de_tenant__7e1c10_idx',
        ),
        migrations.AddField(
            model_name='depense',
            name='categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stations.categoriedepense'),
        ),
        migrations.AddField(
            model_name='depense',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='depenses_creees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='depense',
            name='depense_reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='corrections', to='stations.depense'),
        ),
        migrations.AddField(
            model_name='depense',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depenses', to='stations.station'),
        ),
        migrations.AddField(
            model_name='depense',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='depense',
            name='validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='depenses_validees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='depensejournalier',
            name='categorie',
        ),
        migrations.RemoveField(
            model_name='depensejournalier',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='depensejournalier',
            name='relais',
        ),
        migrations.RemoveField(
            model_name='depensejournalier',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='depensejournalier',
            name='validated_by',
        ),
        migrations.AddIndex(
            model_name='depense',
            index=models.Index(fields=['tenant', 'station'], name='stations_de_tenant__7e4fe3_idx'),
        ),
        migrations.AddIndex(
            model_name='depense',
            index=models.Index(fields=['tenant', 'statut'], name='stations_de_tenant__9243cf_idx'),
        ),
        migrations.DeleteModel(
            name='DepenseJournalier',
        ),
    ]
