# Generated by Django 6.0 on 2026-01-05 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0008_relaisequipe_stock_applique'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='cuve',
        ),
    ]
