# Generated by Django 6.0 on 2026-03-14 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0008_depense_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='depense',
            options={'ordering': ['-date_depense', '-id']},
        ),
    ]
