# Generated by Django 6.0 on 2026-03-14 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0009_alter_depense_options'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='relaisaudit',
            new_name='station_dep_relais__23fb56_idx',
            old_name='stations_re_relais__2672db_idx',
        ),
        migrations.AlterModelTable(
            name='relaisaudit',
            table='station_depenses',
        ),
    ]
