# Generated by Django 6.0 on 2026-01-06 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0009_remove_station_cuve'),
    ]

    operations = [
        migrations.AddField(
            model_name='depotage',
            name='stock_applique',
            field=models.BooleanField(default=False, help_text="Indique si l'impact stock a déjà été appliqué"),
        ),
    ]
