# Generated by Django 6.0 on 2026-03-14 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0010_rename_stations_re_relais__2672db_idx_station_dep_relais__23fb56_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='depense',
            new_name='station_dep_tenant__f9b5ed_idx',
            old_name='stations_de_tenant__7e4fe3_idx',
        ),
        migrations.RenameIndex(
            model_name='depense',
            new_name='station_dep_tenant__b42fa0_idx',
            old_name='stations_de_tenant__9243cf_idx',
        ),
        migrations.RenameIndex(
            model_name='relaisaudit',
            new_name='stations_re_relais__2672db_idx',
            old_name='station_dep_relais__23fb56_idx',
        ),
        migrations.AlterModelTable(
            name='depense',
            table='station_depenses',
        ),
        migrations.AlterModelTable(
            name='relaisaudit',
            table=None,
        ),
    ]
