# Generated by Django 6.0 on 2026-03-14 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0011_rename_stations_de_tenant__7e4fe3_idx_station_dep_tenant__f9b5ed_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='depense',
            new_name='stations_de_tenant__2c6288_idx',
            old_name='station_dep_tenant__f9b5ed_idx',
        ),
        migrations.RenameIndex(
            model_name='depense',
            new_name='stations_de_tenant__00b801_idx',
            old_name='station_dep_tenant__b42fa0_idx',
        ),
        migrations.AlterModelTable(
            name='depense',
            table='stations_depenses',
        ),
    ]
