# Generated by Django 6.0 on 2026-03-14 23:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0012_rename_station_dep_tenant__f9b5ed_idx_stations_de_tenant__2c6288_idx_and_more'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='categoriedepense',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='categoriedepense',
            name='station',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='categories_depense', to='stations.station'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='categoriedepense',
            unique_together={('station', 'nom')},
        ),
        migrations.AddIndex(
            model_name='categoriedepense',
            index=models.Index(fields=['tenant', 'station'], name='stations_ca_tenant__726e4f_idx'),
        ),
        migrations.AddIndex(
            model_name='depense',
            index=models.Index(fields=['station', 'date_depense'], name='stations_de_station_1ac9db_idx'),
        ),
    ]
