# Generated by Django 6.0 on 2026-03-16 10:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances_station', '0002_transactionstation_finances_st_source__c5366c_idx'),
        ('stations', '0013_alter_categoriedepense_unique_together_and_more'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DetteStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.DecimalField(decimal_places=2, max_digits=14)),
                ('montant_initial', models.DecimalField(decimal_places=2, max_digits=14)),
                ('montant_regle', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('PARTIELLE', 'Partiellement réglée'), ('REGLEE', 'Réglée')], default='EN_ATTENTE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReglementDette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='dettejournalier',
            name='stations_de_tenant__52f311_idx',
        ),
        migrations.RemoveIndex(
            model_name='dettejournalier',
            name='stations_de_tenant__e45109_idx',
        ),
        migrations.RenameField(
            model_name='clientstation',
            old_name='valide_par_admin',
            new_name='agree_par_admin',
        ),
        migrations.AlterUniqueTogether(
            name='clientstation',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='clientstation',
            name='cni',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientstation',
            name='station_limitee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stations.station'),
        ),
        migrations.AddField(
            model_name='clientstation',
            name='type_client',
            field=models.CharField(choices=[('PARTICULIER', 'Particulier'), ('ENTREPRISE', 'Entreprise')], default='PARTICULIER', max_length=20),
        ),
        migrations.AddIndex(
            model_name='clientstation',
            index=models.Index(fields=['tenant'], name='stations_cl_tenant__772b73_idx'),
        ),
        migrations.AddIndex(
            model_name='clientstation',
            index=models.Index(fields=['tenant', 'actif'], name='stations_cl_tenant__69d5b8_idx'),
        ),
        migrations.AddIndex(
            model_name='clientstation',
            index=models.Index(fields=['tenant', 'agree_par_admin'], name='stations_cl_tenant__76d801_idx'),
        ),
        migrations.AddField(
            model_name='dettestation',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dettes', to='stations.clientstation'),
        ),
        migrations.AddField(
            model_name='dettestation',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dettestation',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dettes', to='stations.station'),
        ),
        migrations.AddField(
            model_name='dettestation',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='dettestation',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dettes', to='finances_station.transactionstation'),
        ),
        migrations.AddField(
            model_name='reglementdette',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reglementdette',
            name='dette',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reglements', to='stations.dettestation'),
        ),
        migrations.AddField(
            model_name='reglementdette',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='reglementdette',
            name='transaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='reglement_dette', to='finances_station.transactionstation'),
        ),
        migrations.RemoveField(
            model_name='dettejournalier',
            name='client',
        ),
        migrations.RemoveField(
            model_name='dettejournalier',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='dettejournalier',
            name='relais',
        ),
        migrations.RemoveField(
            model_name='dettejournalier',
            name='tenant',
        ),
        migrations.AddIndex(
            model_name='dettestation',
            index=models.Index(fields=['tenant', 'station'], name='stations_de_tenant__909912_idx'),
        ),
        migrations.AddIndex(
            model_name='dettestation',
            index=models.Index(fields=['tenant', 'client'], name='stations_de_tenant__a63c38_idx'),
        ),
        migrations.AddIndex(
            model_name='dettestation',
            index=models.Index(fields=['statut'], name='stations_de_statut_ed0a63_idx'),
        ),
        migrations.DeleteModel(
            name='DetteJournalier',
        ),
    ]
