# Generated by Django 6.0 on 2026-03-16 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0014_dettestation_reglementdette_and_more'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='clientstation',
            constraint=models.UniqueConstraint(fields=('tenant', 'cni'), name='unique_client_cni_par_tenant'),
        ),
    ]
