# Generated by Django 6.0 on 2026-03-16 10:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0015_clientstation_unique_client_cni_par_tenant'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reglementdette',
            name='transaction',
        ),
        migrations.AddField(
            model_name='reglementdette',
            name='mode_paiement',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='reglements_dette', to='stations.modepaiement'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reglementdette',
            name='reference_paiement',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='reglementdette',
            index=models.Index(fields=['tenant'], name='stations_re_tenant__47e367_idx'),
        ),
        migrations.AddIndex(
            model_name='reglementdette',
            index=models.Index(fields=['dette'], name='stations_re_dette_i_cace44_idx'),
        ),
    ]
