# Generated by Django 6.0 on 2026-03-16 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0016_remove_reglementdette_transaction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelaisAudit',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ancien_statut', models.CharField(max_length=20)),
                ('nouveau_statut', models.CharField(max_length=20)),
                ('action', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),

                ('relais', models.ForeignKey(
                    to='stations.relaisequipe',
                    on_delete=django.db.models.deletion.CASCADE
                )),

                ('tenant', models.ForeignKey(
                    to='tenants.tenant',
                    on_delete=django.db.models.deletion.CASCADE
                )),

                ('effectue_par', models.ForeignKey(
                    to='accounts.utilisateur',
                    on_delete=django.db.models.deletion.PROTECT
                )),
            ],
        ),
    ]