# Generated by Django 6.0 on 2026-03-16 23:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0018_add_date_action_relais_audit'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='relaisaudit',
            options={'ordering': ['-date_action']},
        ),
        migrations.RemoveField(
            model_name='relaisaudit',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='relaisaudit',
            name='effectue_par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='relaisaudit',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='relaisaudit',
            name='relais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='stations.relaisequipe'),
        ),
        migrations.AddIndex(
            model_name='relaisaudit',
            index=models.Index(fields=['tenant', 'relais'], name='stations_re_tenant__dbac00_idx'),
        ),
        migrations.AddIndex(
            model_name='relaisaudit',
            index=models.Index(fields=['relais', 'date_action'], name='stations_re_relais__2672db_idx'),
        ),
    ]
