# Generated by Django 6.0 on 2026-03-16 23:42

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0019_alter_relaisaudit_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relaisaudit',
            name='date_action',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now),
            preserve_default=False,
        ),
    ]
