# Generated by Django 6.0 on 2026-03-21 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0020_alter_relaisaudit_date_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.UUIDField()),
                ('station_id', models.UUIDField()),
                ('type', models.CharField(choices=[('RELAIS_A_VALIDER', 'Relais à valider'), ('RELAIS_A_TRANSFERER', 'Relais à transférer'), ('DEPOTAGE_A_VALIDER', 'Dépotage à valider'), ('DEPOTAGE_A_TRANSFERER', 'Dépotage à transférer'), ('STOCK_CRITIQUE', 'Stock critique')], max_length=50)),
                ('message', models.TextField()),
                ('role_cible', models.CharField(choices=[('POMPISTE', 'Pompiste'), ('SUPERVISEUR', 'Superviseur'), ('GERANT', 'Gérant')], max_length=30)),
                ('lien', models.CharField(blank=True, max_length=255, null=True)),
                ('lu', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
