# Generated by Django 6.0 on 2026-06-06 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0021_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='dettestation',
            name='prix_unitaire',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dettestation',
            name='produit',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='dettes', to='stations.produitcarburant'),
            preserve_default=False,
        ),
    ]
