# Generated by Django 6.0 on 2026-06-09 19:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0022_dettestation_prix_unitaire_dettestation_produit'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='relaisecart',
            options={'ordering': ['-date_relais', '-created_at']},
        ),
        migrations.AddField(
            model_name='relaisecart',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ecarts_crees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='relaisecart',
            name='date_relais',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='relaisecart',
            name='montant_encaisse',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='relaisecart',
            name='montant_theorique',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='relaisecart',
            name='relais',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ecarts', to='stations.relaisequipe'),
        ),
        migrations.AddField(
            model_name='relaisecart',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='relaisecart',
            index=models.Index(fields=['tenant', 'date_relais'], name='stations_re_tenant__eb8730_idx'),
        ),
        migrations.AddIndex(
            model_name='relaisecart',
            index=models.Index(fields=['relais'], name='stations_re_relais__423939_idx'),
        ),
    ]
