# Generated by Django 6.0 on 2026-06-15 23:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0023_alter_relaisecart_options_relaisecart_created_by_and_more'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RemboursementEcart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=14)),
                ('date_remboursement', models.DateField()),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='remboursements_ecarts_crees', to=settings.AUTH_USER_MODEL)),
                ('ecart', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='remboursements', to='stations.relaisecart')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='remboursements_ecarts', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remboursements_ecarts', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-date_remboursement'],
            },
        ),
    ]
