# Generated by Django 6.0 on 2026-06-17 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0024_remboursementecart'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientstation',
            name='adresse',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='clientstation',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='clientstation',
            name='registre_commerce',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddConstraint(
            model_name='clientstation',
            constraint=models.UniqueConstraint(condition=models.Q(('email__isnull', False)), fields=('tenant', 'email'), name='unique_client_email_par_tenant'),
        ),
    ]
