# Generated by Django 6.0 on 2026-06-20 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0025_clientstation_adresse_clientstation_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientstation',
            name='cni',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
