# Generated by Django 6.0 on 2026-09-10 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0026_alter_clientstation_cni'),
    ]

    operations = [
        migrations.AddField(
            model_name='dettestation',
            name='relais',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dettes', to='stations.relaisequipe'),
        ),
    ]
