# Generated by Django 6.0 on 2026-09-13 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0028_make_dette_relais_required'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RelaisIndexPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='relais/indexes/%Y/%m/%d/')),
                ('valeur_ocr', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('confiance_ocr', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('date_capture', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('OCR_EFFECTUE', 'OCR effectué'), ('VALIDE', 'Validé'), ('REJETE', 'Rejeté')], default='EN_ATTENTE', max_length=20)),
                ('capture_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='photos_indexes_capturees', to=settings.AUTH_USER_MODEL)),
                ('relais_index', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='photos', to='stations.relaisindex')),
            ],
            options={
                'ordering': ['-date_capture'],
                'indexes': [models.Index(fields=['relais_index', 'date_capture'], name='stations_re_relais__a8fee0_idx'), models.Index(fields=['statut'], name='stations_re_statut_11911f_idx')],
            },
        ),
    ]
