# Generated by Django 6.0 on 2026-09-14 12:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0029_relaisindexphoto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='relaisindexphoto',
            name='commentaire_validation',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='relaisindexphoto',
            name='date_validation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='relaisindexphoto',
            name='valeur_validee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='relaisindexphoto',
            name='validee_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='photos_indexes_validees', to=settings.AUTH_USER_MODEL),
        ),
    ]
