# Generated by Django 6.0 on 2026-09-14 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0030_relaisindexphoto_commentaire_validation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='relaisindex',
            name='retour_en_cuve',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
