# Generated by Django 6.0 on 2026-09-15 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0031_relaisindex_retour_en_cuve'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lubrifiants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('designation', models.CharField(max_length=100)),
                ('nature', models.CharField(help_text='Contenu ou format du lubrifiant : 1L, 2L, 5L, 20L, 500g, etc.', max_length=30)),
                ('unite', models.CharField(help_text='Unité de conditionnement : BIDON, BOUTEILLE, TUBE, CARTOUCHE, etc.', max_length=30)),
                ('prix_vente', models.DecimalField(decimal_places=2, max_digits=12)),
                ('prix_achat', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('seuil_alerte', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lubrifiants', to='tenants.tenant')),
            ],
            options={
                'ordering': ['code'],
                'unique_together': {('tenant', 'code')},
            },
        ),
    ]
