# Generated by Django 6.0 on 2026-09-15 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0032_lubrifiants'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MouvementStockLubrifiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_mouvement', models.CharField(choices=[('ENTREE', 'Entrée'), ('SORTIE', 'Sortie')], max_length=10)),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=12)),
                ('source_type', models.CharField(max_length=50)),
                ('source_id', models.PositiveIntegerField()),
                ('date_mouvement', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lubrifiant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mouvements_stock', to='stations.lubrifiants')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements_stock_lubrifiants', to='stations.station')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements_stock_lubrifiants', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-date_mouvement', '-id'],
                'indexes': [models.Index(fields=['tenant', 'station', 'lubrifiant'], name='stations_mo_tenant__89021a_idx'), models.Index(fields=['source_type', 'source_id'], name='stations_mo_source__70ece7_idx')],
            },
        ),
        migrations.CreateModel(
            name='StockLubrifiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_actuel', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lubrifiant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to='stations.lubrifiants')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks_lubrifiants', to='stations.station')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks_lubrifiants', to='tenants.tenant')),
            ],
            options={
                'ordering': ['station', 'lubrifiant'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'station', 'lubrifiant'), name='unique_stock_lubrifiant_station')],
            },
        ),
    ]
