# Generated by Django 6.0 on 2026-09-15 16:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0033_mouvementstocklubrifiant_stocklubrifiant'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VenteLubrifiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=12)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=12)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=14)),
                ('date_vente', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventes_lubrifiants_creees', to=settings.AUTH_USER_MODEL)),
                ('lubrifiant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventes', to='stations.lubrifiants')),
                ('relais', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventes_lubrifiants', to='stations.relaisequipe')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventes_lubrifiants', to='stations.station')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventes_lubrifiants', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-date_vente', '-id'],
            },
        ),
    ]
