# Generated by Django 6.0 on 2026-09-17 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0035_initialiser_stocks_lubrifiants'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventelubrifiant',
            name='statut',
            field=models.CharField(choices=[('BROUILLON', 'Brouillon'), ('VALIDE', 'Validé'), ('TRANSFERE', 'Transféré')], default='BROUILLON', max_length=20),
        ),
    ]
