# Generated by Django 6.0 on 2026-09-17 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0036_ventelubrifiant_statut'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventelubrifiant',
            name='statut',
        ),
    ]
