# Generated by Django 6.0 on 2026-09-17 19:32

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0037_remove_ventelubrifiant_statut'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrestationBaie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('designation', models.CharField(max_length=100)),
                ('unite', models.CharField(default='UNITE', max_length=30)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestations_baie', to='stations.station')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestations_baie', to='tenants.tenant')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='OperationBaie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=12)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=12)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations_baie_creees', to=settings.AUTH_USER_MODEL)),
                ('relais', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations_baie', to='stations.relaisequipe')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations_baie', to='stations.station')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations_baie', to='tenants.tenant')),
                ('prestation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operations', to='stations.prestationbaie')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AddIndex(
            model_name='prestationbaie',
            index=models.Index(fields=['tenant', 'station', 'actif'], name='idx_prest_baie_station_actif'),
        ),
        migrations.AddConstraint(
            model_name='prestationbaie',
            constraint=models.UniqueConstraint(fields=('tenant', 'station', 'code'), name='unique_prestation_baie_station_code'),
        ),
        migrations.AddIndex(
            model_name='operationbaie',
            index=models.Index(fields=['tenant', 'station'], name='idx_operation_baie_station'),
        ),
        migrations.AddIndex(
            model_name='operationbaie',
            index=models.Index(fields=['relais'], name='idx_operation_baie_relais'),
        ),
        migrations.AddIndex(
            model_name='operationbaie',
            index=models.Index(fields=['prestation'], name='idx_operation_baie_prestation'),
        ),
    ]
