# Generated by Django 6.0 on 2026-09-18 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0038_prestationbaie_operationbaie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='depense',
            name='relais',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='depenses', to='stations.relaisequipe'),
        ),
    ]
