# Generated by Django 6.0 on 2026-09-19 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0039_depense_relais'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelaisJauge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jauge_debut', models.DecimalField(decimal_places=2, max_digits=12)),
                ('jauge_fin', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jauges_relais', to='stations.produitcarburant')),
                ('relais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jauges', to='stations.relaisequipe')),
            ],
            options={
                'db_table': 'stations_relais_jauges',
                'ordering': ['produit__code'],
                'constraints': [models.UniqueConstraint(fields=('relais', 'produit'), name='unique_jauge_produit_relais')],
            },
        ),
    ]
