# Generated by Django 5.2.8 on 2025-12-16 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stations', '0002_remove_ventecarburant_montant_total_and_more'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('RECETTE', 'Recette'), ('DEPENSE', 'Dépense')], max_length=10)),
                ('source_type', models.CharField(max_length=50)),
                ('source_id', models.PositiveIntegerField()),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stations.station')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('source_type', 'source_id')},
            },
        ),
    ]
