# Generated by Django 6.0 on 2026-03-04 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stations', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finance_status', models.CharField(choices=[('PROVISOIRE', 'Provisoire'), ('CONFIRMEE', 'Confirmée')], default='PROVISOIRE', max_length=15)),
                ('type', models.CharField(choices=[('RECETTE', 'Recette'), ('DEPENSE', 'Dépense')], max_length=10)),
                ('source_type', models.CharField(max_length=50)),
                ('source_id', models.PositiveIntegerField()),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('volume', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stations.station')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['tenant', 'date', 'type'], name='finances_st_tenant__aed496_idx'), models.Index(fields=['tenant', 'station'], name='finances_st_tenant__76763f_idx')],
                'unique_together': {('source_type', 'source_id')},
            },
        ),
    ]
