# Generated by Django 6.0 on 2026-02-27 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances_station', '0001_initial'),
        ('stations', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionstation',
            name='volume',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddIndex(
            model_name='transactionstation',
            index=models.Index(fields=['tenant', 'date', 'type'], name='finances_st_tenant__aed496_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionstation',
            index=models.Index(fields=['tenant', 'station'], name='finances_st_tenant__76763f_idx'),
        ),
    ]
