# Generated by Django 6.0 on 2026-03-07 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances_station', '0001_initial'),
        ('stations', '0005_modepaiement_updated_at_alter_modepaiement_actif'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='transactionstation',
            index=models.Index(fields=['source_type', 'source_id'], name='finances_st_source__c5366c_idx'),
        ),
    ]
