# Generated by Django 6.0 on 2026-01-03 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances_station', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionstation',
            name='finance_status',
            field=models.CharField(choices=[('PROVISOIRE', 'Provisoire'), ('CONFIRMEE', 'Confirmée')], default='PROVISOIRE', max_length=15),
        ),
    ]
